//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchitectureTemplate.Infrastructure.WCF.Client.ServiceReferenceProfile {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceProfile.IProfileServiceContract")]
    public interface IProfileServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceContract/GetById", ReplyAction="http://tempuri.org/IProfileServiceContract/GetByIdResponse")]
        ArchitectureTemplate.Infrastructure.WCF.Contracts.Entities.ProfileContract GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceContract/GetById", ReplyAction="http://tempuri.org/IProfileServiceContract/GetByIdResponse")]
        System.Threading.Tasks.Task<ArchitectureTemplate.Infrastructure.WCF.Contracts.Entities.ProfileContract> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceContract/GetByName", ReplyAction="http://tempuri.org/IProfileServiceContract/GetByNameResponse")]
        ArchitectureTemplate.Infrastructure.WCF.Contracts.Entities.ProfileContract GetByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceContract/GetByName", ReplyAction="http://tempuri.org/IProfileServiceContract/GetByNameResponse")]
        System.Threading.Tasks.Task<ArchitectureTemplate.Infrastructure.WCF.Contracts.Entities.ProfileContract> GetByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceContract/GetAll", ReplyAction="http://tempuri.org/IProfileServiceContract/GetAllResponse")]
        ArchitectureTemplate.Infrastructure.WCF.Contracts.Entities.ProfileContract[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServiceContract/GetAll", ReplyAction="http://tempuri.org/IProfileServiceContract/GetAllResponse")]
        System.Threading.Tasks.Task<ArchitectureTemplate.Infrastructure.WCF.Contracts.Entities.ProfileContract[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfileServiceContractChannel : ArchitectureTemplate.Infrastructure.WCF.Client.ServiceReferenceProfile.IProfileServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfileServiceContractClient : System.ServiceModel.ClientBase<ArchitectureTemplate.Infrastructure.WCF.Client.ServiceReferenceProfile.IProfileServiceContract>, ArchitectureTemplate.Infrastructure.WCF.Client.ServiceReferenceProfile.IProfileServiceContract {
        
        public ProfileServiceContractClient() {
        }
        
        public ProfileServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProfileServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ArchitectureTemplate.Infrastructure.WCF.Contracts.Entities.ProfileContract GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<ArchitectureTemplate.Infrastructure.WCF.Contracts.Entities.ProfileContract> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
        
        public ArchitectureTemplate.Infrastructure.WCF.Contracts.Entities.ProfileContract GetByName(string name) {
            return base.Channel.GetByName(name);
        }
        
        public System.Threading.Tasks.Task<ArchitectureTemplate.Infrastructure.WCF.Contracts.Entities.ProfileContract> GetByNameAsync(string name) {
            return base.Channel.GetByNameAsync(name);
        }
        
        public ArchitectureTemplate.Infrastructure.WCF.Contracts.Entities.ProfileContract[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<ArchitectureTemplate.Infrastructure.WCF.Contracts.Entities.ProfileContract[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
