//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchitectureTemplate.Infraestrutura.CrossCutting.Support.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensagensResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagensResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArchitectureTemplate.Infraestrutura.CrossCutting.Support.Resources.MensagensResou" +
                            "rce", typeof(MensagensResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists on the system.
        /// </summary>
        public static string EmailExistente {
            get {
                return ResourceManager.GetString("EmailExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem trying to perform data refresh.
        /// </summary>
        public static string ErroAtualizar {
            get {
                return ResourceManager.GetString("ErroAtualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem trying to register data.
        /// </summary>
        public static string ErroCadastrar {
            get {
                return ResourceManager.GetString("ErroCadastrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem trying to load data to the screen.
        /// </summary>
        public static string ErroCarregar {
            get {
                return ResourceManager.GetString("ErroCarregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading file.
        /// </summary>
        public static string ErroDownload {
            get {
                return ResourceManager.GetString("ErroDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem trying to delete data.
        /// </summary>
        public static string ErroExcluir {
            get {
                return ResourceManager.GetString("ErroExcluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to save data.
        /// </summary>
        public static string ErroSalvar {
            get {
                return ResourceManager.GetString("ErroSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data successfully updated.
        /// </summary>
        public static string SucessoAtualizar {
            get {
                return ResourceManager.GetString("SucessoAtualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data successfully registered.
        /// </summary>
        public static string SucessoCadastrar {
            get {
                return ResourceManager.GetString("SucessoCadastrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data successfully registered, but there was an error sending email.
        /// </summary>
        public static string SucessoCadastrarErroEmail {
            get {
                return ResourceManager.GetString("SucessoCadastrarErroEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully registered data and sent email.
        /// </summary>
        public static string SucessoCadastrarSucessoEmail {
            get {
                return ResourceManager.GetString("SucessoCadastrarSucessoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity completed successfully.
        /// </summary>
        public static string SucessoWorkflow {
            get {
                return ResourceManager.GetString("SucessoWorkflow", resourceCulture);
            }
        }
    }
}
